<a href="https://colab.research.google.com/github/AnnSenina/python_hse_2024/blob/main/notebooks/1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

Сайт: https://numpy.org/

Документация: https://numpy.org/devdocs/user/whatisnumpy.html

Вводный гайд: https://numpy.org/numpy-tutorials/

Наглядно о том, как работает NumPy: https://habr.com/ru/companies/skillfactory/articles/564240/ (Хабр)

In [ ]:
# !pip install numpy
import numpy as np

In [ ]:
# отличия от списков: 1
list1 = [1, 2, 6, 10]
list2 = [66, 54, 989, 1530]

print(list1 + list2)

[1, 2, 6, 10, 66, 54, 989, 1530]


In [ ]:
array1 = np.array([1, 2, 6, 10])
print(array1)

[ 1  2  6 10]


In [ ]:
array2 = np.array([66, 54, 989, 1530])
array1 + array2 # попарно сложились

array([  67,   56,  995, 1540])

In [ ]:
# отличия от списков: 2
list3 = [1, 2, 3, 4, 5, '6']
array3 = np.array([1, 2, 3, 4, 5, '6'])
print(array3)
array3 = np.array([1, 0, 1, 1, 0, False])
print(array3) # только один тип данных

['1' '2' '3' '4' '5' '6']
[1 0 1 1 0 0]


Еще немного об операциях с массивами

In [ ]:
array1 = np.array([1, 2, 6, 10])
array1 > 5 # такая же логика будет при фильтрации датафрейма

array([False, False,  True,  True])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.max(), arr.min(), arr.sum(), arr.mean(), sep=', ')

arr = np.sqrt(arr)
print(arr)

arr = np.sin(arr)
print(arr)

arr = np.cos(arr)
print(arr)

arr = np.log(arr)
print(arr)

arr = np.exp(arr)
print(arr)

5, 1, 15, 3.0
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.84147098 0.98776595 0.98702664 0.90929743 0.78674913]
[0.66636675 0.55055622 0.55117323 0.61430028 0.70615086]
[-0.40591509 -0.59682621 -0.59570612 -0.48727141 -0.34792639]
[0.66636675 0.55055622 0.55117323 0.61430028 0.70615086]


In [ ]:
print(array1 * array2) # объекты попарно перемножились
print(np.dot(array1, array2)) # .dot() - скалярное произведение массивов

[   66   108  5934 15300]
21408


In [ ]:
# идексация
print(array1)
print(array1[0])
print(array1[2:])

[ 1  2  6 10]
1
[ 6 10]


In [ ]:
array4 = np.array([[1,2],[3,4]])
print(array4)
print(array4[0])
print(array4[0][1])

[[1 2]
 [3 4]]
[1 2]
2


In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)
print(matrix[0]) # 1 строка
print(matrix[0,2]) # 3 элемент 1 строки
print(matrix[:, 2]) # 3 столбец

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3
[3 6 9]


In [ ]:
print(array1)
print(array1.shape) # размерность

[ 1  2  6 10]
(4,)


In [ ]:
print(matrix)
print(matrix.shape) # размерность

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


Случайные числа

In [ ]:
a = np.random.rand(10) # 10 случаных чисел
print(a)
b = np.random.rand(3, 2) # 3 строки, 2 столбца слуайных чисел
print(b)

[0.75062945 0.3828088  0.7088944  0.70689522 0.44524351 0.24995969
 0.05684535 0.7781957  0.63415288 0.2627122 ]
[[0.74289817 0.99967497]
 [0.88623247 0.44656734]
 [0.13658744 0.07324454]]


In [ ]:
c = np.random.randint(-10, 10)
print(c)
d = np.random.randint(-10, 10, size=5)
print(d)
e = np.random.randint(-10, 10, size=[2, 5])
print(e)

-7
[  4   8 -10  -2  -8]
[[ 4  6  9 -6 -3]
 [ 3 -6  3 -3  1]]


In [ ]:
# изменение размерности массива
e = np.random.randint(-10, 10, size=[2, 5])
print(e)
print(e.reshape(5, 2))
print(e.reshape(10, 1))
print(e.reshape(1, 10))

[[-5 -3 -2  4 -9]
 [ 1  7  0  3  3]]
[[-5 -3]
 [-2  4]
 [-9  1]
 [ 7  0]
 [ 3  3]]
[[-5]
 [-3]
 [-2]
 [ 4]
 [-9]
 [ 1]
 [ 7]
 [ 0]
 [ 3]
 [ 3]]
[[-5 -3 -2  4 -9  1  7  0  3  3]]


### Практика:

У вас есть массив из миллиона случаных чисел. Умножьте каждое из них на 100 с помощью цикла for / умножения массива numpy, измерив время выполнения команды


In [ ]:
n = np.random.rand(1000000)
n

array([0.17317585, 0.73966029, 0.75080392, ..., 0.00349941, 0.88605461,
       0.24925598])

In [ ]:
%%time
# создайте пустой список и добавьте в него все элементы, умножая каждый на 100


In [ ]:
%%time
# умножьте массив n на 100


In [ ]:
# @title
%%timeit

res = []
for i in n:
  res.append(i * 100)

In [ ]:
# @title
%%time

res = n * 100